chore: updated permissions declaration/description format
lukso-network/LIPs pull request #102
Opened 2022-08-02 09:14 UTC by JeneaVranceanu

# What this PR introduces? 

Updated block of JS code where permissions' names and values are declared, with related documentation.
Moved JS docs for permissions to be on top of each permission constant, not on the same line as the constant as these docs were almost invisible.

![Screenshot 2022-08-02 at 11 56 52](https://user-images.githubusercontent.com/36865532/182338835-f8c89fb8-136d-447e-acbb-dc1a55df2e03.png)

Other related topics to discuss are:
1) the naming of `SUPER_...` permissions;
    Suggest removing `SUPER_` prefix from permissions that have no limitations and adding prefix to permissions that **represent a subset** of current `SUPER_` permissions. 
2) Image with an example of permissions - looks like Alice doesn't have SUPER permissions and the total value of assigned permissions `0x...ffff` shown on the right side of the image is incorrect? In [`lsp-smart-contracts`](https://github.com/lukso-network/lsp-smart-contracts/blob/develop/constants.js#L170) the default `ALL_PERMISSIONS` value is `0x7FBF` which includes all permissions except `DELEGATECALL`, I suppose for security reasons. Bits for permissions that are not declared in this standard are set to 0 in constants in lsp-smart-contracts repository (link is above) but on the image, it feels like all 32 bytes are set to `0xF`. As I recall all bytes were `0xF` initially but later updated to zero out all permissions that do not exist in the standard yet.

2022-08-11 07:15 UTC, CJ42 requested changes
NIce @JeneaVranceanu ! The comments like this looks much better indeed 👌 
I have added some comments.

2022-08-11 07:15 UTC, CJ42 commented on LSPs/LSP-6-KeyManager.md
> +// Allows deploying other contracts through the controlled contract
```suggestion
// Allows deploying new contracts through the controlled contract
```

2022-08-11 07:15 UTC, CJ42 commented on LSPs/LSP-6-KeyManager.md
> +// Allows calling other contracts through the controlled contract
```suggestion
// Allows static calling other contracts through the controlled contract, while restrcting any state modifications during the call (or any subcalls, if present)
```

2022-08-11 07:17 UTC, CJ42 commented
> image with an example of permissions - looks like Alice doesn't have SUPER permissions and the total value of assigned permissions 0x...ffff shown on the right side of the image is incorrect? In [lsp-smart-contracts](https://github.com/lukso-network/lsp-smart-contracts/blob/develop/constants.js#L170) the default ALL_PERMISSIONS value is 0x7FBF which includes all permissions except DELEGATECALL, I suppose for security reasons.

That's a good point, will update to clarify it.

2022-08-11 07:18 UTC, CJ42 commented
@frozeman 

> By the way to change permission permission should not allow adding permissions. Only update existing ones, or removing them.

So like this? ⬇️ 

![Screenshot 2022-08-11 at 08 02 51](https://user-images.githubusercontent.com/31145285/184082893-97567e1c-5859-4033-8483-f6073eb57fac.png)

2022-08-28 10:58 UTC, CJ42 commented
@frozeman reviewed this PR. This can be merged ✅

2022-08-29 08:20 UTC, frozeman approved these changes

2022-08-29 08:20 UTC, merged