[LSP0 and LSP9] document 2 steps process for `renounceOwnership` + add requirement in `transferOwnership`
lukso-network/LIPs pull request #119
Opened 2022-08-30 14:15 UTC by b00ste

## What does this PR introduce?

This PR updated the LIPs according to the latest updates in the smart contracts around `transferOwnership` and `renounceOwnerhsip`.

2022-08-31 09:35 UTC, YamenMerhi requested changes

2022-08-31 09:35 UTC, YamenMerhi commented on LSPs/LSP-0-ERC725Account.md
> +
MUST be called only by the owner.

2022-08-31 09:35 UTC, YamenMerhi commented on LSPs/LSP-0-ERC725Account.md
> +MUST verify if `newOwner` is different from `address(this)`
MUST check that `newOwner` is different from `address(this)` ? maybe

2022-08-31 09:35 UTC, YamenMerhi commented on LSPs/LSP-9-Vault.md
> +#### renounceOwnership
same comments applies here

2022-08-31 10:40 UTC, CJ42 requested changes
added review comments

2022-08-31 10:40 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +The second call MUST happen after a delay of 100 blocks from the first `renounceOwnership(..)` call.
this is a good explanatory sentence 👍  it's easy to read and understand.

2022-08-31 10:40 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +MUST check that `newOwner` is different from `address(this)`
_Suggest changes_

This might read better.

```suggestion
The `newOwner` MUST NOT be `address(this)`
```

2022-08-31 10:40 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +MUST renounce ownership of the contract if and only if the `renounceOwnership(..)` function is called twice.
I don't think we should start the sentence with the word "MUST".

MUST is used to mention a mandatory requirement.

Here, this sentence is to describe the function. So I would suggest more something like this:

```suggestion
Leaves the contract without an owner. Once ownership of the contract is renounced, it MUST NOT be possible to call the functions restricted to the owner only.

Since renouncing ownership a sensitive operation, it SHOULD be done as a two step process by calling  `renounceOwnership(..)` twice. First to initiate the process, second as a confirmation.

_Requirements:_

- MUST be called only by the `owner()` only.
- second call MUST happen after a delay of 100 blocks from the first `renounceOwnership(..)` call.
- If the second call was not done in another 100 blocks after the delay, the renounce ownership phase should be reset.
```

2022-08-31 10:40 UTC, CJ42 commented on LSPs/LSP-9-Vault.md
> +MUST check that `newOwner` is different from `address(this)`.
same comment as above

2022-09-05 09:03 UTC, YamenMerhi approved these changes

2022-09-05 13:26 UTC, CJ42 requested changes

2022-09-05 13:26 UTC, CJ42 commented on LSPs/LSP-9-Vault.md
> +Since renouncing ownership a sensitive operation, it SHOULD be done as a two step process by calling  `renounceOwnership(..)` twice. First to initiate the process, second as a confirmation.
```suggestion
Since renouncing ownership is a sensitive operation, it SHOULD be done as a two step process by calling  `renounceOwnership(..)` twice. First to initiate the process, second as a confirmation.
```

2022-09-05 13:26 UTC, CJ42 commented on LSPs/LSP-9-Vault.md
> +- Second call MUST happen after a delay of 100 blocks from the first `renounceOwnership(..)` call.
same comments as above

2022-09-05 13:30 UTC, CJ42 commented
related to https://github.com/lukso-network/lsp-smart-contracts/pulls?q=is%3Apr+is%3Aclosed

2022-09-06 10:37 UTC, CJ42 approved these changes

2022-09-06 12:13 UTC, frozeman commented on LSPs/LSP-0-ERC725Account.md
> +- The second call MUST happen within a delay of 100 blocks from the first `renounceOwnership(..)` call.
Please correct. It has to happen AFTER the delay if 100 blocks and then within the next 100 blocks

2022-09-06 14:27 UTC, merged