LSP15 Royalties
lukso-network/LIPs pull request #141
Opened 2022-11-23 17:04 UTC by lykhonis

2022-11-25 06:57 UTC, Hugoo commented
Hey cool @lykhonis !
Not sure about the number tho as @CallumGrindle and I have a draft PR for LSP15 too https://github.com/lukso-network/LIPs/pull/133 😊😅🤭

2022-12-07 11:10 UTC, CJ42 reviewed
Thank you @lykhonis for this LIP proposal.

It seems very interesting to me and a very relevant Standard proposal with a lot of potential use cases 🚀 

I have added some review comments.

Let's wait for @frozeman @YamenMerhi @skimaharvey and @b00ste review for more insights.

2022-12-07 11:10 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +- `LSP18RoyaltiesEnforceAtLoss` is a boolean to enforce royalties whenever the NFT is sold at loss.
I am not sure about this data key, as it is related to NFTs and seems to be relevant to a specific application logic.
But there is definitely something relevant around the "enforcing of payment".

Maybe it could be renamed like this? :)

```suggestion
- `LSP18RoyaltiesEnforcePayment` is a boolean to enforce royalties whenever the NFT is sold at loss.
```

TBD for the description.

2022-12-07 11:10 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +Every contract that supports the LSP18DigitalAssetMetadata SHOULD have the following data keys:
```suggestion
Every contract that supports the LSP18Royalties SHOULD have the following data keys:
```

2022-12-07 11:10 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +#### LSP18RoyaltiesMap
I really like this data key.

The concept of points in particular allows some very good precision of the percentage. And it is also common language around financial subjects to say "your portfolio increased by x points, or decreased by y points".

Really like this whole section 😃

2022-12-07 11:10 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +- `type` = the type of a payload:
What does "payload" refer to here?

2022-12-07 11:10 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +```solidity
We are trying to avoid having custom Solidity code in the LIP specs, because we want to emphasize that the LIP specs are language agnostics. So the implementation could be written in any smart contract language (Solidity, Vyper, Fe, Rust, inK, etc...).

Maybe you can add a link instead to your repo? 🙂

2022-12-08 02:50 UTC, lykhonis commented on LSPs/LSP-18-Royalties.md
> +- `type` = the type of a payload:
Correct. For now just these 2 types, this can be extended later for example for a delegated calculation such as type could be an address of an interface (contract) to call calculation logic etc.

2023-02-26 16:15 UTC, YamenMerhi commented on LSPs/LSP-18-Royalties.md
> +    "valueType": "(bytes8,bytes2,bytes4)",
How the last value type is bytes4 where in case of payload 1 the amount will be bytes32 ? Am I missing something ?
Also is there a specific intention having the type as bytes2 and the amount as bytes4/bytes32 ?

2023-02-26 22:58 UTC, HarmonyONELOVER approved these changes

2023-05-25 08:33 UTC, CJ42 requested changes

2023-05-25 08:33 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +The data value MUST be constructed as follows: `bytes8(indexNumber) + bytes2(type) + bytesN`. Where:
I would suggest that the first value in the tuple is a `uint128` (16 bytes long), the same type + bytes length as the index for the `LSP18Royalties[]` Array. 

This will prevent indexes being truncated for index larger than `max(uint64)`.

**Important: I would mark it as a `uint128` ✅ , not as a `bytesN` because of the padding rules (left padded for uint, instead of right padded for bytes)**. The same as it is now with `LSP5ReceivedAssets[]` and `LSP5ReceivedAssetsMap:<address>` when we refactored.

<img width="463" alt="image" src="https://github.com/lukso-network/LIPs/assets/31145285/12153baa-e1dc-46b5-a1a3-03238d0f9a75">


```suggestion
The data value MUST be constructed as follows: `uint128(indexNumber) + bytes2(type) + bytesN`. Where:
```

2023-05-25 08:33 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +    "valueType": "(bytes8,bytes2,bytes4)",
suggested change, so that it reflects properly the type for the Array `index`

```suggestion
    "valueType": "(uint128,bytes2,bytes4)",
```

2023-06-24 07:40 UTC, skimaharvey reviewed
Looks good. 
The only thing is that we might face some real challenges with the notion of "enforcing" royalties. 
Whether we use a percentage or  LYX amount, they can always be bypassed imo.

2023-06-24 07:40 UTC, skimaharvey commented on LSPs/LSP-18-Royalties.md
> +A boolean when `true` to indicate enforcement of royalties even if a NFT is sold at a loss. By default this is `false` and a marktetplace may not enforce royalties.
should we have a datakey that store the latest sold value then?

2023-06-24 07:40 UTC, skimaharvey commented on LSPs/LSP-18-Royalties.md
> +    - `0` = a percentage in points where `100_000` is basis. e.g. `15%` is `15_000` points, and `1.5%` is `1_500` points.
even though it is what make the most sense imo you will never be able to enforce royalties with percentage.
I can always transfer it for 0 value to a "middle" man smart contract that will have some logic that prevent paying royalties

2023-06-24 07:40 UTC, skimaharvey commented on LSPs/LSP-18-Royalties.md
> +    - `1` = a LYX amount in wei.
what will happen if I transfer it for 0 and enforcement is true? who will pay for royalties if `msg.value == 0`?

2023-06-24 11:39 UTC, skimaharvey commented
> > Looks good. The only thing is that we might face some real challenges with the notion of "enforcing" royalties. Whether we use a percentage or LYX amount, they can always be bypassed imo.
> 
> Honestly not sure how to start answering about "enforcement" part. This is a standard describing metadata.

Ah ok sorry thought it was a standard that intended to be implemented

2023-06-24 11:41 UTC, skimaharvey commented on LSPs/LSP-18-Royalties.md
> +    - `1` = a LYX amount in wei.
well my comment is under the `  - `1` = a LYX amount in wei.` I already gave my comment about the percentage enforcement that was not implementable

2023-06-24 11:41 UTC, jakeprins commented on LSPs/LSP-18-Royalties.md
> +    - `0` = a percentage in points where `100_000` is basis. e.g. `15%` is `15_000` points, and `1.5%` is `1_500` points.
> even though it is what make the most sense imo you will never be able to enforce royalties with percentage. I can always transfer it for 0 value to a "middle" man smart contract that will have some logic that prevent paying royalties

This standard is not about always enforcing royalties but about setting royalties settings on the NFT contract, so marketplaces (like universal.page) can enforce them.

2023-06-24 12:24 UTC, jakeprins approved these changes

2023-06-24 12:31 UTC, CallumGrindle commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
The confusion about enforcement comes from this `LSP18RoyaltiesEnforcePayment` key. Enforcement of royalties is tricky because even if your marketplace is enforcing royalties, I can just go to another marketplace which does not enforce royalties so I can buy my NFT for cheaper. 

It's not totally clear how this can be 'standardised' if people can opt out of paying. I.e. whats the point in standardising a metadata key for enforcing royalty payments, if royalty payments cannot be enforced? 

I would suggest at least addressing this in the motivation section of the standard, or find a way this can be implemented at a smart contract level

2023-06-24 12:42 UTC, jakeprins commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
@CallumGrindle, don't you think having some sort of standard around royalties settings is good? So instead of each platform doing its own thing, these settings can be stored on-chain so the marketplaces could act on it?

2023-06-24 12:46 UTC, skimaharvey commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
Alright, got it, so it's standard tailored for centralized marketplaces. 
How utterly refreshing! Because that was the mysterious puzzle piece I was losing sleep over 😄

2023-06-24 12:59 UTC, jakeprins commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
> Alright, got it, so it's standard tailored for centralized marketplaces. How utterly refreshing! Because that was the mysterious puzzle piece I was losing sleep over 😄

Great, let's close the PR. I didn't expect it to take over half a year to come to that conclusion (although I could have known better).

2023-06-24 13:08 UTC, skimaharvey commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
> @CallumGrindle, don't you think having some sort of standard around royalties settings is good? So instead of each platform doing its own thing, these settings can be stored on-chain so the marketplaces could act on it?

It does make sense in the meantime we find a way to enforce them at the SC level

2023-06-24 13:10 UTC, CallumGrindle commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
@lykhonis @jakeprins indeed that makes sense. The question is more about whether it SHOULD be a standard about enforcing royalty payments given those are the keys that are being suggested. 

The issue I see is the following:
- A user creates an NFT collection
- The user selects to enforce royalties 
- There is a marketplace which decides to not enforce royalties
- People start buying the NFTs from this marketplace
- The user gets no royalty payments decide setting that it should be enforced

Its still a useful key for the marketplaces which do adhere to the standard properly, but my worry is that by having 1 marketplace which does not implement the standard, it becomes a problem for the marketplaces which do and the royalty recipients.

Addressing this problem somewhere in the motivation, and stating that it should be handled elsewhere would not hurt

2023-07-01 03:36 UTC, samuel-videau commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
If I can add my neutral input on this @CallumGrindle @skimaharvey @lykhonis @jakeprins. 
I think it does not matter if some marketplaces decide to use it or not. What matters is that marketplaces that want royalties (as it's hardly enforcable), can do it the same way.
Because if not, something we risk to see is having a lot of different keys for the same thing:
`Markerplace1Royalties`, `Marketplace2Royalties`, `Marketplace3Royalties`, and that would be super annoying for NFT collections creators/developers (without even talking about storage waste)

2023-07-01 06:02 UTC, skimaharvey commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
Yes, it is useful but would be better at the smart contract level for the reason @CallumGrindle mentioned... 
Like if I had to sell an NFT I would not shut myself in the foot and would use a marketplace that doesn't enforce them as it increases my chances of selling my NFT. Let's see for how long marketplaces enforce them when they are getting bypassed because they are enforcing something while others don't. 
Anyway, if the marketplaces then we will need a standard for it.

2023-07-01 16:05 UTC, frozeman commented
@lykhonis the focus on the team is the network and up launch right now. Additional standards have less importance internally yet. 

Tho this doesn’t mean you need to close this. Standard debates can happen over months and years and closing and implement as a single project is likely not leading to adoption. 

I personal think the buyable nft standard is the better approach to royalties. But I had no time to look at this proposal in the mean time. 

Also please note. Standard adoption is not determined by a LSP being added to the repo, but by people using it. 
I would suggest you reopen it and start using it as you see fit. And I’ll give my option after the network launch up process is over and I got more mental space for additional ideas. 
(but like I said standards don’t need the lukso team approval, or mine to be used by anyone)

2023-07-03 11:26 UTC, CJ42 reviewed
@jakeprins @lykhonis I am glad to see that this PR was re-opened.

I have left some review comments and would like to merge and accept this proposal, as it seems that everyone agrees on having a standard around Royalties.

There are two main points I would like to point out in particular

**1. having the settings in both the Array + Map seems not necessary**

At least from my viewpoint. I have added in the comments below. I would suggest that the Map data key stores the actual settings, while the array entries stores only the address of the royalty recipients.
But I might lack insights and I don't have the same perspective (seems you have been working on that for a while now).

If you think it's necessary to have the settings in both entries, it would be great if you could explain the reason why it in the standard, so that readers can understand the reason behind this design decision.

**2. About the royalty enforcement debate**

It seems that the royalty enforcement part is what is bringing the most debate in the proposal. I would suggest the following to help everyone reach consensus.

--> add a Security Consideration section (similar to LSP17, see screenshot below), where you mentioned what you said that _"this standard is not about royalty enforcement, but purely for the purpose of setting royalties configurations in a contract"_. You can as well mention the security aspects brought by @skimaharvey and @CallumGrindle in this section, so that developers who will adopt the standards are aware of these points, and understand that **they should use this standard purely for storing royalty settings, and not for enforcing them. Royalty enforcement should be done at the application level (the marketplace itself)**.

![image](https://github.com/lukso-network/LIPs/assets/31145285/9f3726fa-abd9-4fba-acaf-a4f32d6bbb2d)


@frozeman I guess we can always use the Buyable NFT standard in the future as an alternative way around Royalties, so that people have options.

2023-07-03 11:26 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +    - `0` = a percentage in points where `100_000` is basis. e.g. `15%` is `15_000` points, and `1.5%` is `1_500` points.
One thing I am not sure about is that the values `uint8(valueType) + uint256(value)` are present in both:

- the `LSP18RoyaltiesRecipients[]` Array data key
- the `LSP18RoyaltiesRecipientsMap:<address>` data key.

This could be a problem, as both entries have to be in sync. For instance, what happen if royalty settings get updated and let's say:
- in the Array data key you have `valueType == 0` (a percentage for the type of royalty) (assumed to be the correct setting after update) ✅ 
- in the Map data key you have `valueType == 1` (a fixed LYX amount) ❌ (old setting that was not updated).

I would suggest 3 options:

_option 1: keep it as it is, the settings are in both the Array and Map data key, but the standard specify that **they MUST always be in sync (so the implementation code MUST ensure that)**_

_option 2: remove these two values from the Array data key (the Array data key contains only the Royalty recipient's address), and only the Map contains the royalty settings (same as it is done in LSP5, LSP10 and LSP12)_

![image](https://github.com/lukso-network/LIPs/assets/31145285/7941c138-8cbc-478a-892a-9ae1f67e7f06)

2023-07-03 11:26 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +A boolean when `true` to indicate enforcement of royalties even if a NFT is sold at a loss. By default this is `false` and a marktetplace may not enforce royalties.
```suggestion
A boolean when `true` to indicate enforcement of royalties even if a NFT is sold at a loss. By default, this is `false`, and a marketplace may not enforce royalties.
```

2023-07-04 06:12 UTC, samuel-videau commented
After re-reading the standard, I'm just wondering the need of 3 different keys for that, I think one would be more than enough.

Firstly, I think `LSP18RoyaltiesEnforcePayment` doesn't make sense, as if the other royalty keys are filled, then it means you want marketplaces to enforce royalties. I won't create a NFT, add royalties on it but then say "no do not apply those royalties", if that value is on false, then why adding royalties to the contract ? So basically, marketplaces should assume that if the royalty keys are filled, then creators want them to be applied.

Secondly, the two other keys are really redondant. Is the `tandardInterfaceId` really important?
Let's say it is, why not having only the `LSP18RoyaltiesRecipients[]` key with the following format:
```
{
    "name": "LSP18RoyaltiesRecipients[]",
    "key": "0xfdd4e98ba62fdcf79cfde4cfe031a71195ae21ff3d0e29f79db24f2fe9ceb59b",
    "keyType": "Array",
    "valueType": "(address,bytes4,uint16,uint32)",
    "valueContent": "(Address,Bytes4,Number,Number)"
}
```

Using this key only you would have all the info you need to add royalties (or am I missing something?). And the value would be packed in less than 32 bytes

2023-07-04 07:09 UTC, CJ42 commented
@samuel-videau The Map data key is needed because otherwise to get the royalty settings of an address, you would have to loop through the entire array in storage. Which can be big a uses a lot of gas.

2023-07-04 07:18 UTC, samuel-videau commented
> @samuel-videau The Map data key is needed because otherwise to get the royalty settings of an address, you would have to loop through the entire array in storage. Which can be big a uses a lot of gas.
> 
> You could put everything in one data key and allow it. But the standard needs to specify this aspect and make developers aware of it.

But the thing is that here you still need to loop through the array to know the addresses that should have royalties anyway

2023-07-04 07:24 UTC, CJ42 commented
That's actually a pretty good point. I agree about this.

2023-07-07 08:35 UTC, skimaharvey commented
> 3. LSP18RoyaltiesEnforcePayment is needed as it instructs a marketplace to enforce royalties regardless whether a user is selling it at a profit or at a loss. If this key is set to false, and user is selling at a loss, a marketplace should not enforce royalties and allow sale without them.

How will the concept of "selling at a loss" will work cross-marketplaces since the value is not part of any events? 
For example, I buy my NFT on opensea and sell it on looksrare. How will Looksrare know about the price I purchased my nft for? Should looksrare rely on opensea api 👀

2023-07-23 11:24 UTC, FamilyNFT commented on LSPs/LSP-18-Royalties.md
> +    "name": "LSP18RoyaltiesEnforcePayment",
@lykhonis @jakeprins, I think this would be a far more impactful standard if we we're to enforce royalties at the core level. We should be putting the creators at the forefront as we're The New Creative Economy. Simply creating a standard for marketplaces will only repeat what has happened in the past where different marketplaces will try get market share by removing royalties, making creators lose out at the end.....

If you guys truly value creators like you said, we should be thinking at the fundamental levels. This will also not just benefit creators but Universal Page aswell, since you'll be removing upcoming competition that tries to compete using "royalties" as their edge.

Any chance you guys can make the necessary changes to make this enforceable at the smart contract level please @skimaharvey @CallumGrindle. We would love to implement this in Family

2023-10-19 12:19 UTC, frozeman commented
@lykhonis sorry for the long wait, we now had a proper look internally and the standard looks great, as separating issuers and royalties makes sense.

We would have a few points that I will comment on the doc.

2023-10-19 12:33 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +requires: LSP2, LSP4
Why is LSP4 required here? I think it is not, we can remove this.

2023-10-19 12:33 UTC, CJ42 commented on LSPs/LSP-18-Royalties.md
> +The data value MUST be constructed as follows: `address(recipient) + uint32(value)`. Where:
What is the rationale for choosing `uint32` as valueType?

2023-10-19 12:42 UTC, frozeman commented
After additional thinking.
1. doing automatic push payments of NFT sales will require the payout smart contract to iterate over the array keys, which can be very costly.
2. Using `Array` keyType was probably chosen so that it supports many royalty receivers.


I see two scenarios
1. a few royalty receivers. -> Then an compact array as `valueContent` is better and keyType `Singleton`. As this is one call, and easy to iterate over.
2. have many royalty receivers -> Its better to point to a LSP7 contract, where each balance references the percentage e.g. 1000 tokens available, and balance means a percentage of this.

For small amount of royalty receivers its easy todo a "push" payment distribution.  (just look up the royalties array)

For large royalty receivers group, you need to use a "pull" contract. e.g.
on NFT purchase, the royalties get put into a claim contract and based on the LSP7 royalty balances, users can withdraw their part.

To make both of these use cases possible i would suggest:

**Small number of royalties receivers**

```js
{
    "name": "LSP18InternalRoyaltiesRecipients",
    "key": "0xxxxxxxxx",
    "keyType": "Singleton",
    "valueType": "(address,uint32)[CompactBytesArray]",
    "valueContent": "(Address,Number)"
}
```

[Compact byte array](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#bytescompactbytesarray) allows for more simple encoded arrays.

basically you get back in one single smart contract call `[(reciver1, percentage), (reciver2, percentage), ...]`

**Large number of royalties receivers**

```js
{
    "name": "LSP18ExternalRoyaltiesRecipients",
    "key": "0xxxxxxxxx",
    "keyType": "Singleton",
    "valueType": "(bytes4,uint32,address)",
    "valueContent": "(Bytes4,Number,Address)"
}
```

- `Bytes4` is the interfaceId, of the linked contract
- `Number` is the percentage of royalties that get distributed to all holders of the linked contract (to be used by the distribution contract, which could also be the same as the linkedin contract )
- `Address` The address is a LSP7 or any other contract, that contains the royalty distribution

2023-10-24 18:36 UTC, lykhonis commented
> After additional thinking.
> 
> 1. doing automatic push payments of NFT sales will require the payout smart contract to iterate over the array keys, which can be very costly.
> 2. Using `Array` keyType was probably chosen so that it supports many royalty receivers.
> 
> I see two scenarios
> 
> 1. a few royalty receivers. -> Then an compact array as `valueContent` is better and keyType `Singleton`. As this is one call, and easy to iterate over.
> 2. have many royalty receivers -> Its better to point to a LSP7 contract, where each balance references the percentage e.g. 1000 tokens available, and balance means a percentage of this.
> 
> For small amount of royalty receivers its easy todo a "push" payment distribution. (just look up the royalties array)
> 
> For large royalty receivers group, you need to use a "pull" contract. e.g. on NFT purchase, the royalties get put into a claim contract and based on the LSP7 royalty balances, users can withdraw their part.
> 
> To make both of these use cases possible i would suggest:
> 
> ```js
> {
>     "name": "LSP18RoyaltiesRecipients",
>     "key": "0xxxxxxxxx",
>     "keyType": "Singleton",
>     "valueType": "(bytes4,address,uint32)[CompactBytesArray]",
>     "valueContent": "(Bytes4,Number,Address)"
> }
> ```
> 
> [Compact byte array](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#bytescompactbytesarray) allows for more simple encoded arrays.
> 
> basically you get back in one single smart contract call `[(reciver1, percentage), (reciver2, percentage), ...]`
> 
> **Small number of royalties receivers** Simply put an array of UPs or EOAs in there
> 
> **Large number of royalties receivers** Just put the address of an LSP7 contract with `claim/withdraw` function, that distributes based on tokens held in the LSP7.
> 
> you can even have a combination of both now.
> 
> * `Bytes4` is the interfaceId, of the linked contract (TBD if that's necessary)
> * `Number` is the percentage of royalties that get distributed to the address
> * `Address` The address of receiver(), which could also be a LSP7 royalty claim contract(s) or any other contract, that contains the royalty distribution system
> 
> **Benefits**
> 
> * allows for cheaper sort contract calls for small amount of royalties receivers
> * allows for very large group where royalties can even be changing over time, as its could be a LSP7
> 
> side note: i would remove the dependency on LSP4, that's necessary
> 
> -> Concerning enforcement data key, what's your thinking here? @lykhonis

I think indeed this is a good change. We can start slowly with a small number of receivers (most likely the most common case anyway) as a single key/value.

Enforcing part was more marketplace dependent feature. Rational was for a creator to opt-in to not charge royalties if a NFT is sold at a loss. If I to buy nft at $10 and sell at $5, I will not pay 10% royalties thus loosing even more.

2023-10-24 18:53 UTC, jakeprins commented
> @frozeman I guess we can always use the Buyable NFT standard in the future as an alternative way around Royalties, so that people have options.

@CJ42 For the buyable NFT standard. Will there be a way to enforce a fee for the curator? Enforceable royalties for NFT creators are great, but without enforceable royalties/fees for platform creators (like Universal Page), there is no incentive to create the products to discover and trade these assets. This lack of incentive could hurt the NFT creators (and overall ecosystem) even more so I'm interested to hear what you think about this.

2023-10-29 06:53 UTC, lykhonis commented
We addressed compact array solution in the LSP and implemented it locally in solidity and typescript. I believe it is a good baseline and start.

2023-10-29 08:41 UTC, frozeman commented
@jakeprins sorry for the late response. In the future feel free to ping me in DM on discord. So I see it and answer faster.

In my opinion, the “en force” part should be in the marketplace itself. Not the standard. In my opinion, it should be by the fault always requiring royalties. But if it’s on the marketplace level, if anyway depends on the marketplace implementation . If we later add the ability to buy and sell the NFT directly over the nft smart contract, then royalties will be always enforced, or, however, the order book contract attached to the NFT decides to do it. 
The entries here in the NFT are purely information as of now, and it depends on the marketplace or future standards to use it in whatever way they want anyway.

2023-10-29 10:21 UTC, jakeprins commented
> @jakeprins sorry for the late response. In the future feel free to ping me in DM on discord. So I see it and answer faster.
> 
> In my opinion, the “en force” part should be in the marketplace itself. Not the standard. In my opinion, it should be by the fault always requiring royalties. But if it’s on the marketplace level, if anyway depends on the marketplace implementation . If we later add the ability to buy and sell the NFT directly over the nft smart contract, then royalties will be always enforced, or, however, the order book contract attached to the NFT decides to do it. The entries here in the NFT are purely information as of now, and it depends on the marketplace or future standards to use it in whatever way they want anyway.

@frozeman Yes indeed. However, the original question was more about the "buyable" NFT standard and how it could enforce "royalties" for the creators of NFT platforms (known as platform fees). I think it's important to incentivize the creation and maintenance of these platforms, especially for applications that require a lot of work and money to build and run. Otherwise, the "royalty" problem would simply be shifted from NFT creators to app creators, which I think would not result in a healthy ecosystem in the long run (assuming it will gets widely adopted). At the very least, it would force app creators to adopt a different business model. But if we look at "fee-less" marketplaces, this can quickly become questionable. For example, a lot of platforms launch (mostly useless) tokens which the community often pays the price for. Or you could go the Web2 way of filling everything with ads and tracking scripts (also not that cool). If there's one thing people should have learned from Web2, it's that _if you're not paying for the product, you are the product_. Therefore I believe the "fee" model is (just like creator royalties) a better option for app creators. Anyway, this is just my personal opinion, and I'm obviously biased as I want Universal Page to succeed and stay around for a long time.

2023-10-29 13:45 UTC, FamilyNFT commented
@jakeprins from my perspective the buyable standard doesn't need to enforce royalties for curators/middleman since this is already built in to the overall infrastructure of blockchains. What I mean by this is that end users still needs to pay gas/fees to be able to use the blockchain therefore as a curator/platform they inherently benefit from this feature. So they either abstract it away from end users via ads or simply pay for user's gas by taking a fee. And in my humble opinion, curators should play the game of AND not OR for the best business results ;)

2024-01-11 11:37 UTC, CJ42 commented
> @jakeprins sorry for the late response. In the future feel free to ping me in DM on discord. So I see it and answer faster.
> 
> In my opinion, the “en force” part should be in the marketplace itself. Not the standard. In my opinion, it should be by the fault always requiring royalties. But if it’s on the marketplace level, if anyway depends on the marketplace implementation . If we later add the ability to buy and sell the NFT directly over the nft smart contract, then royalties will be always enforced, or, however, the order book contract attached to the NFT decides to do it. The entries here in the NFT are purely information as of now, and it depends on the marketplace or future standards to use it in whatever way they want anyway.

I also see this enforcable part in the Marketplace itself, so that different market places can come up with different solutions for enforcing royalties, which would create different business models that NFT creators could choose from.

The Marketplace could create a LSP17 Extension contract in the form of the order book that contains the royalty enforcement logic (that the Marketplace itself has defined). This way, we can differentiate between the storage layer (the royalty distribution settings, percentage, etc...), and the logic layer (in the LSP17 extension itself). An NFT collection could then decide to move overtime from one royalty distribution medium to another, if it finds a new one more efficient, with additional benefits.

2024-03-25 20:31 UTC, Hugoo commented on LSPs/LSP-18-Royalties.md
> +A compact byte array allows optinally to store additional fields if needed. Required fields are: `interfaceId` and `recipient`. The `points` field is optional and if not provided it is assumed to be
```suggestion
A compact byte array allows optionally to store additional fields if needed. Required fields are: `interfaceId` and `recipient`. The `points` field is optional and if not provided it is assumed to be `0` points.
```

2024-03-25 21:35 UTC, Hugoo commented on LSPs/LSP-18-Royalties.md
> +- `interfaceId` = an interface identifing a recipient of royalties. If the interface is not known, it is assumed to be `0xffffffff`.
Does it mean that if it is set to `0xffffffff`, then the interfaceId check is skipped? Which means royalties will be sent to any kind of contract or EOA defined as `recipient`?

2024-04-10 12:26 UTC, frozeman commented on LSPs/LSP-18-Royalties.md
> +#### LSP18RoyaltiesEnforcePayment
I am not sure about this, because its not clear what this is good for, if interfaces/websites/trading contracts anyway make the decision to enfore or not by themselves.

2024-06-17 10:47 UTC, CJ42 approved these changes

2024-06-17 10:49 UTC, merged

2024-06-17 10:50 UTC, CJ42 commented
Super! First community standard 🎉