feat: change element length size to 2 bytes
lukso-network/LIPs pull request #158
Opened 2023-01-11 07:05 UTC by skimaharvey

After some internal discussions, we decided that limiting the maximum element size to 255 was not enough and updated the length element size to a `bytes2` value (initially byte1)

2023-01-16 11:14 UTC, CJ42 requested changes

2023-01-16 11:14 UTC, CJ42 commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +> **Note:** the maximum length of each element is 65536, because two bytes (equivalent to a `uint16`) are used to store the length of each element and the maximum value of a `uint16` is 65536.
65,536 will overflow.

The max value is `0xffff` = 65,535.

```suggestion
> **Note:** the maximum length of each element is 65535, because two bytes (equivalent to a `uint16`) are used to store the length of each element, and the maximum value of a `uint16` is 65535.
```

See here: https://www.rapidtables.com/convert/number/hex-to-decimal.html

![image](https://user-images.githubusercontent.com/31145285/212664749-8480a000-85d5-4cfc-bf1e-4da4803d3d0a.png)

2023-01-16 11:14 UTC, CJ42 commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +> **Note:** because two bytes are used to store the length of each element, the maximum `N` length allowed is 65536 (two bytes are equivalent to the maximum value of a `uint16` is 65536)
same comment as above

```suggestion
> **Note:** because two bytes are used to store the length of each element, the maximum `N` length allowed is 65535 (two bytes are equivalent to the maximum value of a `uint16` is 65535)
```

2023-01-16 11:14 UTC, CJ42 commented on LSPs/LSP-2-ERC725YJSONSchema.md
>    vv                vv                vv
We need to arrange the pointers here, to make them point correctly to the two bytes lengths.

```
  vvvv                vvvv                vvvv
0x000811223344556677880008cafecafecafecafe0008beefbeefbeefbeef
```

2023-01-16 11:14 UTC, CJ42 commented on LSPs/LSP-6-KeyManager.md
>  <1c> <bytes4 allowedInterfaceId> <bytes20 allowedAddress> <bytes4 allowedFunction>
```suggestion
<001c> <bytes4 allowedInterfaceId> <bytes20 allowedAddress> <bytes4 allowedFunction>
```

2023-01-24 13:16 UTC, CJ42 approved these changes

2023-01-24 13:18 UTC, YamenMerhi approved these changes

2023-01-24 14:09 UTC, CJ42 approved these changes

2023-01-24 14:44 UTC, frozeman approved these changes

2023-01-24 14:45 UTC, merged