LSP2: (related to [WP-D24]) Improve description of `valueContent` for the case of arrays
lukso-network/LIPs pull request #160
Opened 2023-01-11 15:18 UTC by CJ42

- improve the generic description of `valueContent` in LSP2, including a basic example of displaying information in a user interface.

- add extra note about `valueContent` in the case of arrays.

2023-01-11 17:37 UTC, b00ste commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +Knowing how to interpret the data retrieved under a data key is relevant to understand how to handle it. Interfaces can use the `valueContent` to adapt their behaviour or know how to display data fet
```suggestion
Knowing how to interpret the data retrieved under a data key is the first step in understanding how to handle it. Interfaces can use the `valueContent` to adapt their behaviour or know how to display data fetched from an ERC725Y smart contract. 
```

2023-01-11 17:38 UTC, b00ste approved these changes

2023-01-12 05:58 UTC, YamenMerhi approved these changes

2023-01-12 08:58 UTC, frozeman requested changes
lets add an example

2023-01-12 15:04 UTC, frozeman approved these changes

2023-01-12 15:07 UTC, merged