[WP-L14] LSP-6: `AddressPermissions:AllowedCalls:<address>` should use `bytes28[]` or `bytes28[CompactBytesArray] rather than bytes[CompactBytesArray]`
lukso-network/LIPs pull request #161
Opened 2023-01-11 15:38 UTC by CJ42

Based on the recommendation in the title, update the LSP2 Schema for `AddressPermissions:AllowedCalls:<address>` with the following modification:

- describe as a tuple for each types in `valueType` and `valueContent` instead of `bytes28`.

- Fixed some typos

2023-01-11 17:34 UTC, b00ste approved these changes

2023-01-11 17:35 UTC, b00ste commented
Not sure about 'infos' over 'information'  on the lines 333, 363, 378, 403. Other than that LGTM.

2023-01-12 05:58 UTC, YamenMerhi approved these changes

2023-01-12 09:01 UTC, frozeman commented on LSPs/LSP-6-KeyManager.md
>  <1c> <bytes4 allowedInterfaceId> <bytes20 allowedAddress> <bytes4 allowedFunction>
Its would be good to show an example with multiple elements like
```
<1c> <bytes4 allowedInterfaceId> <bytes20 allowedAddress> <bytes4 allowedFunction> <1c> ... <1c> ...
```

so people understand how compatnByteArrays work

2023-01-12 09:01 UTC, frozeman requested changes
lets edit the example

2023-01-12 12:11 UTC, CJ42 commented on LSPs/LSP-6-KeyManager.md
>  <1c> <bytes4 allowedInterfaceId> <bytes20 allowedAddress> <bytes4 allowedFunction>
@frozeman there is actually an examples for AllowedCalls that include 2 x allowed calls restrictions.
![image](https://user-images.githubusercontent.com/31145285/212063307-0ad20cac-5012-43d6-996c-4548a6baf14d.png)

2023-01-12 20:46 UTC, skimaharvey approved these changes

2023-01-16 13:51 UTC, merged