Document LSP14 Type IDs overriding
lukso-network/LIPs pull request #165
Opened 2023-01-18 12:41 UTC by b00ste

### What does this PR introduce?

In this PR the following changes are introduced:

- Adding a note in LSP14 about the possibility of overriding the Type IDs of the hooks called by `transferOwnership(..)` and `acceptOwnership(..)`
- Adding requirements in LSP0 and LSP9 about overriding the Type IDs in LSP14

2023-01-18 12:49 UTC, YamenMerhi commented on LSPs/LSP-0-ERC725Account.md
>  This function is part of the [LSP14] specification.
Just to be consistent, please also do in LSP9

```suggestion
This function is part of the [LSP14] specification, with additional requirements as follows:
```

2023-01-18 12:49 UTC, YamenMerhi commented on LSPs/LSP-0-ERC725Account.md
>  This function is part of the [LSP14] specification.
Just to be consistent, please also do in LSP9

```suggestion
This function is part of the [LSP14] specification, with additional requirements as follows:
```

2023-01-18 12:55 UTC, YamenMerhi approved these changes

2023-01-18 13:01 UTC, CJ42 requested changes

2023-01-18 15:49 UTC, CJ42 approved these changes

2023-01-18 17:42 UTC, skimaharvey approved these changes

2023-01-24 08:44 UTC, frozeman approved these changes

2023-01-24 08:44 UTC, merged