Draft: new LSP8 Standard changes
lukso-network/LIPs pull request #198
Opened 2023-03-29 11:11 UTC by CJ42

Can be viewed better in the branch: https://github.com/lukso-network/LIPs/blob/lsp8-changes/LSPs/LSP-8-IdentifiableDigitalAsset.md

2023-04-05 04:18 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> -#### LSP8MetadataJSON:TokenId
Why is this key being deleted?

2023-04-05 04:21 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +#### LSP8MetadataURI:<tokenId>
```suggestion
#### LSP8TokenURI:<tokenId>
```

2023-04-05 04:23 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "valueContent": "(Bytes4,URI)"
```suggestion
    "valueContent": "(Bytes4,JSONURL)"
```

2023-04-05 04:23 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "name": "LSP8MetadataURI:<address|uint256|bytes32|string>",
```suggestion
    "name": "LSP8TokenURI:<address|uint256|bytes32|string>",
```

2023-04-05 04:24 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "valueContent": "(Bytes4,URI)"
Why are we removing the JSONURL there?

2023-04-05 04:26 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +- TokenId type `5`
```suggestion
- TokenId type `5`
e.g. `http://mybase.uri/my_string`
```

2023-04-05 04:29 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "valueContent": "(Bytes4,URI)"
We're not using that anymore? Because now that means the only way to have verified metadata is to have it's hash as a tokenId ? It's really restrictive as then the metadata will never be able to change (is it wanted?)

2023-04-05 04:31 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "valueContent": "(Bytes4,URI)"
Again, wee have to think about several use cases, so basically now we loose verifiability when upgradable metadata? I'm good with it actually but it's smth to keep in mind. And to be truly honest, I really doubt people will use tokenIds as hashed metadata

2023-04-05 04:34 UTC, samuel-videau commented
Really unclear what the token id type `3` stands for nor why it is asked to add a `bytes4` hashedfunction before the URI. Not specified anywhere how the metadata should be verified nor where the hashed value should be stored. So basically with the current PR we remove any verifiability on LSP8 metadata. References to old keys (e.g. `LSP8MetadataAddress:<address|uint256|bytes32>`) at the end of the file

2023-04-05 04:38 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "valueContent": "(Bytes4,URI)"
And the idea of having a tokenId as hashed metadata was useful for the baseURI. But here there is no necessity for. Though it keep consistency, but it's also really less clear and by that, we restrict having verifiability to only when we have a tokenId as hashed metadata here. So for me it's a big regression

2023-04-05 05:32 UTC, CJ42 commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "valueContent": "(Bytes4,URI)"
Unless I misunderstood, I thought we would use (Bytes4,URI) so that if we want verifiability, we can store the hash function in the bytes4 tuple.

As first 4 bytes of hash("keccak256(utf8)").

So if we want verifiability, we can use the hash function known + hash the JSON file to get the JSONURI, otherwise we use a plain URI

2023-04-05 05:34 UTC, CJ42 commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "name": "LSP8MetadataURI:<address|uint256|bytes32|string>",
Agree on this change. It will be a simpler metadata name.

2023-04-05 12:05 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "valueContent": "(Bytes4,URI)"
Ah alright, it's not specified anywhere so had no way to know. Have to add more explainations on that. And it's (Bytes4,URI) 
so we need to know it's either URI either JSONURI

2023-04-05 12:40 UTC, CJ42 commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> -#### LSP8MetadataJSON:TokenId
What I understand is that these 2 x data keys below are deprecated as they are replaced by `LSP8MetadataURI` / `LSP8TokenURI`.

Or maybe I am missing something?

<img width="976" alt="image" src="https://user-images.githubusercontent.com/31145285/230082929-9913e728-772e-48f6-b40f-f6f98db48abc.png">

2023-04-05 13:41 UTC, frozeman commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +### ERC725Y Data Keys - Minting Contract (Collection)
Lets not use the word "Minting Contract (Collection)"

and LSP8 is not necessarily a collection contract. Please remove

2023-04-05 13:49 UTC, frozeman requested changes
We need to improve the explanations

2023-04-05 13:49 UTC, frozeman commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +#### LSP8MetadataURI:<tokenId>
`LSP8MetadataURI`, as off chain only meta data or related information is stored, and not the token itself.
whats the thinking behind the `LSP8TokenURI` suggestion?

2023-04-05 13:49 UTC, frozeman commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +If the tokenId is a hash (type 3), the first `bytes4` in the tuple of the `valueType`/`valueContent` represents the hash function.
`(type 3)` -> `(LSP8TokenIdType 3)`

2023-04-05 13:49 UTC, frozeman commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "name": "LSP8MetadataURI:<address|uint256|bytes32|string>",
What else than meta data can be stored under the URI?

2023-04-05 13:49 UTC, frozeman commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "valueContent": "(Bytes4,URI)"
Samuel you were not there in the calls, but it shows the explanation is lacking.
Why not using JSON URL, as some URLs might be alterable, and thats preferred. 
the first 4 bytes mean the hash function, if its set to `0x00000000` and the token id is not a hash, then the url can be a changeable one, for NFTs that change over time for example.

same applies for baseURI.

@CJ42 this needs to be better explained.

2023-04-06 08:24 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +#### LSP8MetadataURI:<tokenId>
What you mean by "not the token itself" ? This key is the replacement of `LSP8MetadataJSON:<address|uint256|bytes32>` right ? If yes then it's the key to store metadata for a specific token. So tokenURI make more sense for me and keep consistency with what existing in ERC721 (either baseURI & tokenURI)

2023-04-06 08:26 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +#### LSP8MetadataURI:<tokenId>
> `LSP8MetadataURI`, as off chain only meta data or related information is stored, and not the token itself. whats the thinking behind the `LSP8TokenURI` suggestion?

Ok but yeah I get your point, but let's stay consistent regarding the other key `LSP8MetadataBaseURI`, and call this one `LSP8MetadataTokenURI` or something like that

2023-04-06 08:31 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    "name": "LSP8MetadataURI:<address|uint256|bytes32|string>",
> What else than meta data can be stored under the URI?

Yup `LSP8MetadataTokenURI:<address|uint256|bytes32|string>` make more sense to keep consistent with the other `LSP8MetadataBaseURI`

2023-04-12 07:34 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> -    "name": "LSP4Metadata",
Hmmm not sure we should remove `LSP4Metadata`, I mean this key will still be used to describe the contract metadata. Or maybe you consider we don't need to put it here as it's already in the `LSP4` doc? If it's the case then we at least need to reference it (same for LSP4TokenName actually (so could be good to reference to `LSP4` doc))

2023-04-12 07:47 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    - if the tokenId is any other LSP8TokenIdType: MUST be `0x00000000`.
Well I still don't understand why we do that here, it was useful for the baseURI as we can t store JSONUrls. But here we could store a JSONUrl no matter the tokenIdType. Now it's a big regression as with this updated key, we loose verifiability on all the other tokenIds than the tokenId 3. Though it's adding consistency with the baseURI key

2023-04-12 09:42 UTC, CJ42 commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> -    "name": "LSP4Metadata",
@samuel-videau it is mentioned further down below, in the section **LSP8 TokenId Metadata**

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/31145285/231419599-9da525c3-a894-44d1-b14f-03c4ed78b86b.png">

https://github.com/lukso-network/LIPs/blob/240d8baad573ef06cef8a5bdf6da5246f907967c/LSPs/LSP-8-IdentifiableDigitalAsset.md#lsp8-tokenid-metadata

2023-04-12 09:50 UTC, frozeman commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    - if the tokenId is any other LSP8TokenIdType: MUST be `0x00000000`.
because there is a big argument for changeable NFTs, where the meta data can be altered by an algorithm ,therefore producing different files. we shouldn't enforce hash referenced files, but rather give it as a feature.

2023-04-12 10:03 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    - if the tokenId is any other LSP8TokenIdType: MUST be `0x00000000`.
Alright I see

2023-04-12 10:04 UTC, samuel-videau commented on LSPs/LSP-8-IdentifiableDigitalAsset.md
> +    - if the tokenId is any other LSP8TokenIdType: MUST be `0x00000000`.
Makes sense, as JSON url would force changeable NFTs to update the metadata keys all the time

2023-04-12 11:05 UTC, merged

2023-04-12 11:05 UTC, frozeman commented
Accidentally merged now, lets open a new PR for changes @CJ42