Update LSP0 and LSP6 to new behavior
lukso-network/LIPs pull request #200
Opened 2023-04-10 20:27 UTC by YamenMerhi

## What does this PR introduce ?

- Update LSP0
- Update LSP6

2023-04-11 11:13 UTC, CJ42 requested changes

2023-04-11 11:13 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +- If the interfaceId being queried is not supported in the contract or inherited contracts, the data key attached below MUST be retreived from the ERC725Y storage.
```suggestion
- If the interfaceId being queried is not supported by the contract or inherited contracts, the data key attached below MUST be retrieved from the ERC725Y storage.
```

2023-04-11 11:13 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +```json
I think we should rather move this entire section in the LSP17 standard. Because the extended behaviour of `supportInterface` with extension will apply to any contract that implements LSP17.

We cannot have in the future to duplicate this description for any single standard that implements LSP17.

2023-04-11 12:35 UTC, YamenMerhi commented on LSPs/LSP-0-ERC725Account.md
> +```json
To be discussed if this a native behavior to LSP17

2023-04-11 15:46 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +This standard, defines a blockchain account system to be used by humans, machines, or other smart contracts.
```suggestion
This standard, defines a blockchain-based account system that can be used by humans, machines, or other smart contracts.
```

2023-04-11 15:46 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +- **Attaching information**: via [ERC725Y](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-725.md#erc725y), allowing the addition of information even after deployment
let's add the dot `.` at the end of each sentence.

```suggestion
- **Attaching information**: via [ERC725Y](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-725.md#erc725y), allowing the addition of information even after deployment.
```

2023-04-11 15:46 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +- **Executing**: via [ERC725X](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-725.md#erc725x), enabling the account to call functions on other contracts with different operations, transfer nat
```suggestion
- **Executing**: via [ERC725X](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-725.md#erc725x), enabling the account to call functions on other contracts with different operations, transfer native tokens to addresses, and deploy new contracts.
```

2023-04-11 15:46 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +- **Receiving notifications of incoming and outgoing transactions**: via [LSP1-UniversalReceiver](./LSP-1-UniversalReceiver.md), enabling the account to be aware of assets or followers or any other i
```suggestion
- **Receiving notifications of incoming and outgoing transactions**: via [LSP1-UniversalReceiver](./LSP-1-UniversalReceiver.md), enabling the account to be aware of assets or any other information and react accordingly (e.g., denying specific tokens)
```

2023-04-11 15:46 UTC, CJ42 commented on LSPs/LSP-0-ERC725Account.md
> +- **Owning and controlling the account**: via [LSP14-Ownable2Step](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-14-Ownable2Step.md), ensuring secure two-step ownership transfers
```suggestion
- **Owning and controlling the account**: via [LSP14-Ownable2Step](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-14-Ownable2Step.md), ensuring transfer of ownership is secured through a 2-step process.
```

2023-04-18 08:18 UTC, CJ42 approved these changes

2023-04-18 08:19 UTC, merged