Rename LSP3 Standard to Profile-Metadata
lukso-network/LIPs pull request #220
Opened 2023-08-02 09:06 UTC by YamenMerhi

2023-08-03 10:29 UTC, CJ42 requested changes
We also need to remove the word `"Universal"` in these sections below:

<img width="1126" alt="image" src="https://github.com/lukso-network/LIPs/assets/31145285/fb915b38-6e0a-40d1-8e6e-a70c899f456f">

<img width="1045" alt="image" src="https://github.com/lukso-network/LIPs/assets/31145285/fb6f622b-9272-4c70-9f8f-13e991d904e9">

2023-08-03 10:29 UTC, CJ42 commented on LSPs/LSP-10-ReceivedVaults.md
> +To be able to display received vaults in a profile we need to keep track of all received vaults contract addresses. This is important for [LSP0-ERC725Account](./LSP-0-ERC725Account.md), but also Asse
Nice catch! 👌 

I am not sure about the last part of this sentence, it's a bit confusing.

_but also Assets smart contracts via [LSP5-ReceivedAssets](./LSP-5-ReceivedAssets.md) Standard._

Especially the _"via LSP5-REceivedAssets Standard"_

2023-08-03 10:29 UTC, CJ42 commented on LSPs/LSP-10-ReceivedVaults.md
> +To be able to display received vaults in a profile we need to keep track of all received vaults contract addresses. This is important for [LSP0-ERC725Account](./LSP-0-ERC725Account.md), but also Asse
Suggesting to remove the last part to keep the focus of the specs on Vaults.

```suggestion
To be able to display received vaults in a profile we need to keep track of all received vaults contract addresses. This is important for [LSP0-ERC725Account](./LSP-0-ERC725Account.md).
```

2023-08-03 10:29 UTC, CJ42 commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +[LSP0-ERC725Account](./LSP-0-ERC725Account.md#implementation) and [LSP4-DigitalAsset-Metadata](./LSP-4-DigitalAsset-Metadata.md#implementation).
I would suggest removing this change. Here the point of LSP2 is to describe that it can be used to describe Metadata Standards.

LSP3 is a Metadata standard like LSP4. 

While LSP0 is a conglemerate of multiple standards, and not necessarely a metadata standards (the metadata keys are there in LSP0 because they come from the specs of the other standards, not from LSP0 directly).

2023-08-03 10:38 UTC, CJ42 commented
@YamenMerhi @frozeman @skimaharvey @b00ste 

With this change, I believe we will have to change the following data key ❌ 

```json
    {
        "name": "SupportedStandards:LSP3UniversalProfile",
        "key": "0xeafec4d89fa9619884b60000abe425d64acd861a49b8ddf5c0b6962110481f38",
        "keyType": "Mapping",
        "valueType": "bytes4",
        "valueContent": "0xabe425d6"
    },
```

To the following (I have also changed the hash for the second word to keep the first 20 bytes of `keccak256("LSP3Profile")`

```json
    {
        "name": "SupportedStandards:LSP3Profile",
        "key": "0xeafec4d89fa9619884b600005ef83ad9559033e6e941db7d7c495acdce616347",
        "keyType": "Mapping",
        "valueType": "bytes4",
        "valueContent": "0xabe425d6"
    },
```

2023-08-08 08:41 UTC, b00ste approved these changes

2023-08-08 09:09 UTC, CJ42 approved these changes

2023-08-08 09:09 UTC, merged