refactor: Simplify deployment info for LSP16 & LSP23
lukso-network/LIPs pull request #302
Opened 2024-08-26 11:53 UTC by b00ste

# What does this PR introduce?

This PR simplifies the information related to deploying LSP16 & LSP23 at vanity addresses.

2024-08-27 08:12 UTC, skimaharvey approved these changes

2024-08-27 08:40 UTC, YamenMerhi approved these changes

2024-09-03 18:07 UTC, JeneaVranceanu commented on LSPs/LSP-16-UniversalFactory.md
> +To deploy this follower system on other chains please see the [deployment section](#deployment).
Don't understand how follower system is related to LSP-16 and 23 in this context.
Nothing about "follower system" is mentioned or explained here or in LSP-23.

2024-10-21 13:13 UTC, CJ42 requested changes

2024-10-21 13:13 UTC, CJ42 commented on LSPs/LSP-16-UniversalFactory.md
> +To deploy this follower system on other chains please see the [deployment section](#deployment).
```suggestion
```

2024-10-21 13:13 UTC, CJ42 commented on LSPs/LSP-16-UniversalFactory.md
> +The `LSP16UniversalFactory` is deplpoyed at [`0x1600016e23e25D20CA8759338BfB8A8d11563C4e`](https://explorer.lukso.network/address/0x1600016e23e25D20CA8759338BfB8A8d11563C4e) on LUKSO using the [Nick
```suggestion
The `LSP16UniversalFactory` is deployed at [`0x1600016e23e25D20CA8759338BfB8A8d11563C4e`](https://explorer.lukso.network/address/0x1600016e23e25D20CA8759338BfB8A8d11563C4e) on LUKSO using the [Nick Factory contract](https://github.com/Arachnid/deterministic-deployment-proxy/tree/master). The following explains how to deploy `LSP16UniversalFactory` at the same address on other EVM networks.
```

2024-10-21 13:13 UTC, CJ42 commented on LSPs/LSP-23-LinkedContractsFactory.md
> +The `LSP23LinkedContractsFactory` is deplpoyed at [`0x2300000A84D25dF63081feAa37ba6b62C4c89a30`](https://explorer.lukso.network/address/0x2300000A84D25dF63081feAa37ba6b62C4c89a30) on LUKSO using the
```suggestion
The `LSP23LinkedContractsFactory` is deployed at [`0x2300000A84D25dF63081feAa37ba6b62C4c89a30`](https://explorer.lukso.network/address/0x2300000A84D25dF63081feAa37ba6b62C4c89a30) on LUKSO using the [Nick Factory contract](https://github.com/Arachnid/deterministic-deployment-proxy/tree/master). The following explains how to deploy `LSP23LinkedContractsFactory` at the same address on other EVM networks.
```

2024-10-21 13:16 UTC, CJ42 approved these changes

2024-10-21 13:16 UTC, merged