Refactor/lsp2
lukso-network/LIPs pull request #55
Opened 2022-01-09 23:23 UTC by CJ42

# What does this PR introduce?

Improve readability, layout and structure of LSP2 - ERC725Y JSON Schema.

For a preview, see here: https://github.com/CJ42/LIPs/blob/refactor/lsp2/LSPs/LSP-2-ERC725YJSONSchema.md

## New Features

- For `valueType`
  - added `boolean` type
  - added signed integers `intN`
  - [x] replaced `uint256` with `uintN`
  - [x] replaced `bytes32` with `bytesN`
- For `valueContent`
  - added `Boolean`
  - [x] added `BitArray`
  - used keyword `Literal` for constant value content like `0x13456ABCD...`

## Content

Most of the content has been improved, by adding more precisions on specifications and requirements. 

- improved content for **Simple Summary**, **Abstract** and **Motivation**.
- added table with quick links at the top for `name`, `key`, `keyType`, `valueType` and `valueContent`.
- created sections for `name`, `key`, `keyType`, `valueType` and `valueContent`
- added tables with available types for `keyType`, `valueType` and `valueContent`
- improved description of construction keys for **Array** and mappings
- [x] added explanation for `BitArray`

2022-01-09 23:24 UTC, CJ42 commented
awaiting for #54 to be merged

2022-01-10 10:10 UTC, JeneaVranceanu requested changes

2022-01-10 10:10 UTC, JeneaVranceanu commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +In scenarios where an ERC725Y key is part of an LSP Standard (Metadata standard), the key `name` SHOULD be comprised of the following: `LSP{N}{KeyName}`, where
Do we need `(Metadata standard)`? There is a high chance I do not understand the actual reason behind this clarification.

2022-01-10 10:10 UTC, JeneaVranceanu commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +*e.g.:* `MyColourTheme`, `LSP4TokenName`
> *e.g.:* `MyColourTheme` (isn't a part of any LSP), `LSP4TokenName` (part of LSP4 standard).

2022-01-10 10:10 UTC, JeneaVranceanu commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +- `KeyName`: a short name for the ERC725Y key.
> a name for the underlying value. Should hold the meaning of the value.

It is a little bit recursive, I think. `KeyName` is part of what comprises an `ERC725Y` key.

2022-01-10 10:15 UTC, CJ42 commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +ERC725Y enables storing any data in a smart contract as `bytes32` > `bytes` key-value pairs.
Even better would be `bytes32` => `bytes` (to related to the underlying `mapping` used by Solidity

2022-01-10 10:21 UTC, CJ42 commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +In scenarios where an ERC725Y key is part of an LSP Standard (Metadata standard), the key `name` SHOULD be comprised of the following: `LSP{N}{KeyName}`, where
yes should be removed

2022-01-10 10:22 UTC, CJ42 commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +*e.g.:* `MyColourTheme`, `LSP4TokenName`
instead `part of a LSP Standard`. For the rest perfect 👍

2022-01-10 11:11 UTC, frozeman commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +<table style="text-align: center">
I am not a fan of this table. Can we please use mark-down tables and make it so that we have:

ValueType | Description \n list of values 
KeyType | Description \n List of keytypes
...

2022-01-10 12:17 UTC, frozeman approved these changes

2022-01-11 07:52 UTC, CJ42 commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +The benefit of such schema is to allow interfaces or smart contracts to better decode (read, parse and interpret) the data stored in an ERC725Y contract. On the other hand, it also enables interfaces
@JeneaVranceanu I have just added _less error-prone due to knowing data types upfront_

2022-01-11 08:18 UTC, JeneaVranceanu commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +- for `Array` keys (see [`Array`](#array) section for more details)
> - for `Array` keys (see [`Array`](#array) section for more details) **a combination of:**

2022-01-11 08:50 UTC, JeneaVranceanu commented on LSPs/LSP-2-ERC725YJSONSchema.md
> +    "valueContent": "Address" // describes the value of each elements
There is a typo. It should be `... element` (single form) on both 215 and 216 lines.

2022-01-11 11:25 UTC, merged